// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.27.3
// source: common/time.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "api.common";

export interface CreatedAt {
  value: Timestamp | undefined;
}

export interface UpdatedAt {
  value: Timestamp | undefined;
}

export const API_COMMON_PACKAGE_NAME = "api.common";
