// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.27.3
// source: api.proto

/* eslint-disable */

export const protobufPackage = "api";

export const API_PACKAGE_NAME = "api";
