// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.27.3
// source: models/account.proto

/* eslint-disable */
import { CreatedAt, UpdatedAt } from "../common/time";

export const protobufPackage = "api.models";

export interface Account {
  id: number;
  name: string;
  createdAt: CreatedAt | undefined;
  updatedAt: UpdatedAt | undefined;
}

export const API_MODELS_PACKAGE_NAME = "api.models";
